title: Heba Rasmy
email: your-email@example.com
description: >
  Computer Science & AI Graduate | Builder of Intelligent Systems | NLP, CV, and RAG Enthusiast
github_username: hebarasmy
linkedin_username: heba-rasmy

theme: minima
markdown: kramdown
